spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:3306/print
    username: "root"
    password: "root"
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update