server:
  servlet:
    context-path: "/printing"
  port: 8080

spring:
  profiles:
    active: dev

  jpa:
    show-sql: false

randomid: "0123456789abcdef"

security:
  username: "print"
  password: "print"

ironpdfKEY: "IRONSUITE.NETFLIXCREYTOB.GMAIL.COM.14892-BFD3CB80AE-BMZ7DZBMXANTXVLZ-T7BYYSCT5D4U-M6I3CU4HRMSB-4MTIDVMTRBTT-ZPVJTCU7R2DJ-DTI27PTXCUGL-VPHAUM-TDKWVUDV4OWMUA-DEPLOYMENT.TRIAL-3DK6AW.TRIAL.EXPIRES.17.JUN.2024"
